config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#new'  
  get 'messages/show'

  get 'friendships/create'

  get 'sessions/new'
  


  get 'users/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :passwordresets

  resources :users do
     resources :friendships do
     resources :messages
   end
end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
  end

  def new

     
     @rec = (Conversation.where('(user_id= ? AND exchange_id= ?) OR (user_id= ? AND exchange_id= ?)',params[:user_id],params[:friendship_id],params[:friendship_id],params[:user_id])).first
     if @rec
     @messages=@rec.messages

 else
 	@messages=[]
 end
        
    @user_rec = User.find(params[:user_id])
    @friend_rec = User.find(params[:friendship_id])







  end

  def create
  	
    @converse = (Conversation.where('(user_id= ? AND exchange_id= ?) OR (user_id= ? AND exchange_id= ?)',params[:user_id],params[:friendship_id],params[:friendship_id],params[:user_id])).first
      
    if @converse
    	  
              conv = @converse.messages.build(:user_id=> current_user.id, msg: params[:message][:msg])
              if conv.save
              	 flash[:notice] = "Message successfully sent"
              	 redirect_to new_user_friendship_message_path
              end
    else
              conv = current_user.conversations.build(:exchange_id => params[:friendship_id])
                 if conv.save
                   	msg_build = conv.messages.build(:user_id=> current_user.id, msg: params[:message][:msg])
                  
                      if msg_build.save
                      	    flash[:notice] = "Message successfully sent"
				        	redirect_to new_user_friendship_message_path
				      end
                  end
    end

  end

  private

  def create_message()
      #messages.build(:user_id=> current_user.id, msg: params[:message][:msg])
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/new.html.erb
<table>
     <tr>
    <th>Conversation</th>
    <th></th>
         <% @messages.each do |message| %>
         <tr>
         <% if (message.user_id == current_user.id)  %>
         <td><%= @user_rec.firstname     %>  says :</td>
         <% else  %>
         <td><%=  @friend_rec.firstname%> says :</td>
         <% end%>


      <td><%= message.msg %></td><td>&nbsp;&nbsp;</td><td><%= message.created_at %> </td>
      </tr>
     
     </tr>
    <% end %> 
</table>




<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:message, url: user_friendship_messages_path ) do |f| %>
     

      <%= f.label :Messages %><br>
      <%= f.text_field :msg, class: 'form-control' %><br><br>


      <%= f.submit "Send", class: "btn btn-primary" %><br>
    <% end %>
    <li><%= link_to "Back", user_path(params[:user_id], params[:friendship_id]) %></li>
    
  </div>
</div>