config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#new'  
  get 'messages/show'

  get 'friendships/create'

  get 'sessions/new'
  


  get 'users/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :passwordresets

  resources :users do
     resources :friendships do
     resources :messages
   end
end
end

app/models/user.rb
class User < ApplicationRecord
   
  mount_uploader :image, ImageUploader

   has_many :friendships
   has_many :friends, :through => :friendships

=begin
   has_many :reverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
   has_many :reverse_friends, :through => :reverse_friendships, :source => :user
=end

   has_many :requested_friendships, -> { where(status: "pending")}, :class_name => "Friendship",:foreign_key => "friend_id"
   has_many :requested_friends, :through => :requested_friendships, :source => :user


   has_many :pending_friendships, -> { where(status: "requested")}, :class_name => "Friendship",:foreign_key => "friend_id"
   has_many :pending_friends, :through => :pending_friendships, :source => :user


   has_many :accepted_friendships, -> { where(status: "accepted")}, :class_name => "Friendship",:foreign_key => "friend_id"
   has_many :accepted_friends, :through => :accepted_friendships, :source => :user

  ###################################################
   
    has_many :conversations
    has_many :exchanges, :through => :conversations
  


  ####################################################

   
   

    attr_accessor :remember_token
    has_secure_password
    
      before_save { self.email = email.downcase }
  	validates :firstname, presence: true, length: { maximum: 50 }
        validates :lastname, presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  	validates :password, presence: true, length: { minimum: 6 }


  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)

    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  
  end
  
   # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
  	@user = User.find(params[:id])
    @all_users = User.where.not(id: @user.id ) - @user.friends

    @accepted_friends = @user.accepted_friends
    @pending_friends = @user.pending_friends 
    @requested_friends = @user.requested_friends  

  end


  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
    	  flash[:success] = "Welcome to the Sample App!"
          redirect_to @user
    else
      render 'new'
    end
  end

  
  def edit
    @user = User.find(params[:id])
  end
  

  def update
  @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
    else
      render 'edit'
    end
  end


  private

    def user_params
      params.require(:user).permit(:firstname, :lastname, :username, :email, :password,
                                   :image )
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>



<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     

      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %><br><br>

      <%= f.label :email %><br>
      <%= f.email_field :email, class: 'form-control' %><br><br>

      <%= f.label :password %><br>
      <%= f.password_field :password, class: 'form-control' %><br><br>

      <%= f.label :password_confirmation, "Confirmation" %><br>
      <%= f.password_field :password_confirmation, class: 'form-control' %><br><br>

      <%= f.submit "Save changes", class: "btn btn-primary" %><br>
    <% end %>

    
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this article from being saved:
<h1>Sign up</h1>


<% if @user.errors.any? %>
    <div id="error_explanation">
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :firstname %><br>
      <%= f.text_field :firstname, class: 'form-control' %><br><br>
      
      <%= f.label :lastname %><br>
      <%= f.text_field :lastname, class: 'form-control' %><br><br>
      
       <%= f.label :username %><br>
      <%= f.text_field :username, class: 'form-control' %><br><br>

      <%= f.label :email %><br>
      <%= f.email_field :email, class: 'form-control' %><br><br>

      <%= f.label :password %><br>
      <%= f.password_field :password, class: 'form-control' %><br><br>

      <%= f.label :password_confirmation, "Confirmation" %><br>
      <%= f.password_field :password_confirmation, class: 'form-control' %><br><br>

      <%= f.label :image %><br>
      <%= f.file_field :image, class: 'form-control' %><br><br>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<li><%= link_to "Back", login_path %></li>

app/views/users/show.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>




 <% if logged_in? %>
<h3>Welcome  <%= image_tag(@user.image.url)%><%= @user.firstname  %><%= @user.lastname  %></h3><br>


<table>
     <tr>
    <th>Active Friends</th>
    <th></th>
        </tr><% @accepted_friends.each do |friend| %>
    <tr>
      <td><%= friend.firstname %>  <%= friend.lastname %></td>
      
      <td><%= link_to "Send Messages", new_user_friendship_message_path(@user.id,friend.id) %></td><br>
      <td><%= link_to "Unfriend",user_friendship_path(@user.id,friend.id), :method => :delete, data: { confirm: 'Are you sure?' } %></td><br>
     </tr>
    <% end %> 
   </table>


    <table>
     <tr><br><br>
    <th>Listing Of All Users</th>
    <th></th>
        </tr><% @all_users.each do |user| %>
    <tr>
      <td><%= user.firstname %></td>
      <td><%= user.lastname %></td>
      <td><%= link_to "Send Friend Request", user_friendships_path(:user_id => current_user.id ,:friend_id => user), :method => :post %></td><br>
    </tr>
  <% end %> 
</table>

    <table>
     <tr><br><br>
    <th>Accept Friend Request</th>
    <th></th>
        </tr><% @pending_friends.each do |user| %>
    <tr>
      <td><%= user.firstname %>  <%= user.lastname %></td>
      <!--<td><%= user.lastname %></td>-->
      <td><%= link_to "Accept Request", user_friendship_path(@user.id, user.id), :method => :patch %></td><br>
      <td><%= link_to "Decline",  user_friendship_path(@user.id,user.id), :method => :delete,data: { confirm: 'Are you sure?' } %></td><br>
     </tr>
    <% end %> 
   </table>


   <table>
     <tr><br><br>
    <th>Friend Request Sent to</th>
    <th></th>
        </tr><% @requested_friends.each do |user| %>
    <tr>
      <td><%= user.firstname %>  <%= user.lastname %></td>
      <!--<td><%= user.lastname %></td> -->
      
     </tr>
    <% end %> 
   </table>






         <!-- <li><%= link_to "Views Users",'#' %></li>  -->
          
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
               
              </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>



 <% end %>