config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#new'  
  get 'messages/show'

  get 'friendships/create'

  get 'sessions/new'
  


  get 'users/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :passwordresets

  resources :users do
     resources :friendships do
     resources :messages
   end
end
end

app/controllers/passwordresets_controller.rb
class PasswordresetsController < ApplicationController
	def new
	end

	def create
       @user = User.find_by(user_params)
       

       if @user
          render 'show'   
       else
          render 'new'
       end
	end

	def show

        
             render 'new'
        
    end

	private

    def user_params
      params.require(:passwordresets).permit(:email )
    end
end

app/helpers/passwordresets_helper.rb
module PasswordresetsHelper
end

app/views/passwordresets/new.html.erb
<h2>Password Reset</h2>
<h3>Enter your email</h3>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:passwordresets, url: passwordresets_path ) do |f| %>
     

      <%= f.label :email %><br>
      <%= f.text_field :email, class: 'form-control' %><br><br>


      <%= f.submit "Check", class: "btn btn-primary" %><br>
    <% end %>
    <li><%= link_to "Back", '#' %></li>
    
  </div>
</div>

app/views/passwordresets/show.html.erb
<h1>Generate</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     

      <%= @user.firstname %><br><br><br>
      
      <%= f.label :security_answer %><br>
      <%= f.email_field :email, class: 'form-control' %><br><br>

      <%= f.label :password %><br>
      <%= f.password_field :password, class: 'form-control' %><br><br>

      <%= f.label :password_confirmation, "Confirmation" %><br>
      <%= f.password_field :password_confirmation, class: 'form-control' %><br><br>

      <%= f.submit "Save changes", class: "btn btn-primary" %><br>
    <% end %>

    
  </div>
</div>